### ISSUE TITLE
Error when trying to import Kenkyusha EPWING

### ISSUE THREAD

**Issue by mirukushake** [FooSoft/yomichan-import#3]
I am on Mac OS X Sierra (10.12.3) trying to import the EPWING version of Kenkyusha 5th edition. Zero-epwing processing seems to go well, but I can never get it to start the server. 

On my first try, I got this error:

```users-MacBook-Air:Documents user$ ./yomichan-import Kenkyusha/5
2017/03/14 07:27:54 converting 'Kenkyusha/5' to '/var/folders/0r/fpk8v_nn6z70bqlrkxw_7q0r0000gn/T/yomichan_tmp_557844224' in 'epwing' format...
2017/03/14 07:27:54 invoking zero-epwing from '/Users/user/Documents/bin/darwin/zero-epwing'...
2017/03/14 07:28:27 completed zero-epwing processing
runtime: stat overflow: val 33838, n 65536
```

I tried again, replacing the program and bin folder with fresh files, and received this error. 

```users-MacBook-Air:Documents user$ ./yomichan-import Kenkyusha/5
2017/03/14 07:33:06 converting 'Kenkyusha/5' to '/var/folders/0r/fpk8v_nn6z70bqlrkxw_7q0r0000gn/T/yomichan_tmp_098786236' in 'epwing' format...
2017/03/14 07:33:06 invoking zero-epwing from '/Users/user/Documents/bin/darwin/zero-epwing'...
2017/03/14 07:33:25 completed zero-epwing processing
mach error semaphore_signal: 15
fatal error: mach error

runtime stack:
runtime.throw(0x358f48, 0xa)
	/usr/lib/go-1.6/src/runtime/panic.go:547 +0x79
runtime.macherror(0xf, 0x36ca20, 0x10)
	/usr/lib/go-1.6/src/runtime/os1_darwin.go:209 +0x96
runtime.mach_semrelease.func1()
	/usr/lib/go-1.6/src/runtime/os1_darwin.go:459 +0x2b
runtime.systemstack(0x10733ee0)
	/usr/lib/go-1.6/src/runtime/asm_386.s:329 +0x77
runtime.mach_semrelease(0x0)
	/usr/lib/go-1.6/src/runtime/os1_darwin.go:459 +0x37
runtime.semawakeup(0xfe9d9d0)
	/usr/lib/go-1.6/src/runtime/os1_darwin.go:22 +0x15
runtime.unlock(0x4e9c70)
	/usr/lib/go-1.6/src/runtime/lock_sema.go:109 +0x134
runtime.incidlelocked(0xffffffff)
	/usr/lib/go-1.6/src/runtime/proc.go:3353 +0x4d
runtime.retake(0xb2879b90, 0x14ab91cd, 0x14ab91cd)
	/usr/lib/go-1.6/src/runtime/proc.go:3576 +0x164
runtime.sysmon()
	/usr/lib/go-1.6/src/runtime/proc.go:3511 +0x1ee
runtime.mstart1()
	/usr/lib/go-1.6/src/runtime/proc.go:1098 +0xc6
runtime.mstart()
	/usr/lib/go-1.6/src/runtime/proc.go:1068 +0x53

goroutine 1 [runnable]:
syscall.Syscall(0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/syscall/asm_darwin_386.s:17 +0x5
syscall.Close(0xa, 0x0, 0x0)
	/usr/lib/go-1.6/src/syscall/zsyscall_darwin_386.go:404 +0x3f
os.(*file).close(0x150a4020, 0x0, 0x0)
	/usr/lib/go-1.6/src/os/file_unix.go:140 +0x4a
os.(*File).Close(0x23dfe798, 0x0, 0x0)
	/usr/lib/go-1.6/src/os/file_unix.go:132 +0x45
main.writeDb.func2(0x33cfe0, 0x4, 0x21abc000, 0x3cb07, 0x4baaa, 0x19, 0x0, 0x0)
	/home/alex/projects/go/src/github.com/FooSoft/yomichan-import/common.go:158 +0x49c
main.writeDb(0x107122d0, 0x47, 0x107142d0, 0x2a, 0x33d2b0, 0x6, 0x21abc000, 0x3cb07, 0x4baaa, 0x0, ...)
	/home/alex/projects/go/src/github.com/FooSoft/yomichan-import/common.go:180 +0x18d
main.epwingExportDb(0xbffffd06, 0xb, 0x107122d0, 0x47, 0x107142d0, 0x2a, 0x2710, 0x0, 0x0, 0x0)
	/home/alex/projects/go/src/github.com/FooSoft/yomichan-import/epwing.go:201 +0x1300
main.exportDb(0xbffffd06, 0xb, 0x107122d0, 0x47, 0x33b6b0, 0x6, 0x0, 0x0, 0x2710, 0x0, ...)
	/home/alex/projects/go/src/github.com/FooSoft/yomichan-import/main.go:57 +0x423
main.main()
	/home/alex/projects/go/src/github.com/FooSoft/yomichan-import/main.go:112 +0x57c
```

Any ideas on how to fix this?

**Comment by FooSoft** [comment]
It looks like a bad build was generated (I probably updated to a different version of Go with some outdated packages still lying around). I uploaded the new binaries for darwin, try them out and let me know if they work for you (works in Sierra on VirtualBox).

**Comment by mirukushake** [comment]
Sorry for the late reply, but it worked. Thanks!

**Comment by FooSoft** [comment]
:+1:
